QUESTION 1 2 

In [2]:
!pip install gapminder

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
!pip install see

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from gapminder import gapminder
from see import see

In [16]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
data = gapminder
data.head(10)

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [17]:
data.describe()

year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
pd.DataFrame(data_scaled)
# statistics of scaled data
pd.DataFrame(data_scaled).describe()

QUESTION 3 4

In [1]:
from IPython.display import clear_output
import numpy as np
import random
import time
import gym

In [ ]:
env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [ ]:

action_size = env.action_space.n  # 6 = 0,1,2,3,4,5 as given in question
print("Action size ", action_size) 

state_size = env.observation_space.n  # 500 size as given in question
print("State size ", state_size)

Action size  6
State size  500


In [ ]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:

#searched for these values
episodes = 30000            
max_steps = 1000            
lr = 0.3                    
decay_fac = 0.00001         
gamma = 0.90                

In [ ]:
for episode in [30000]:
    
    state = env.reset() 
    done = False        
    lr -= decay_fac     
    step = 0
    
    if lr <= 0:
        break
        
    for step in range(max_steps):
        action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        if done == True:
            qtable[state, action] = qtable[state, action]+lr*(reward+gamma*0-qtable[state,action])
            break
        else:
            qtable[state, action] = qtable[state,action]+lr*(reward+gamma*np.max(qtable[new_state,:])-qtable[state,action])
        state = new_state
        
    episode += 1


In [ ]:

state = env.reset()
env.render()
done = False
total_reward = 0

while(done == False):
    action = np.argmax(qtable[state,:])
    state, reward, done, info = env.step(action) 
    total_reward += reward 
    time.sleep(0.5)
    clear_output(wait=True)
    env.render()
    print('Reward = ', total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Reward =  10
