# QUESTION 2 K201716 KNN

In [36]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets

In [48]:
dataset = datasets.load_iris()
X, y = dataset.data, dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1074)


In [38]:
def euclidean(x1, x2):
    distance = np.sqrt(np.sum((x1-x2)**2))
    return distance

In [57]:
from collections import Counter
class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self.helper_predict(x) for x in X]
        return predictions

    def helper_predict(self, x):
        # computing the distance
        distances = [euclidean(x, x_train) for x_train in self.X_train]
    
        # getting the closest k neighbours
        k_indices = np.argsort(distances)[:self.k] #gets k closest neighbours
        k_nearest_labels = [self.y_train[i] for i in k_indices] 

        # most common class 
        most_common = Counter(k_nearest_labels).most_common()
        return most_common[0][0]

In [58]:
clf = KNN(k=9)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print("list of predictions:\n", predictions)
accuracy = np.sum(predictions == y_test) / len(y_test)
print("\nAccuracy of our model: ", accuracy)
matrix= confusion_matrix(y_test, predictions)
print("\nConfusion Matrix: \n", matrix)

list of predictions:
 [2, 1, 1, 0, 1, 1, 2, 2, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 2, 0, 2, 2]

Accuracy of our model:  0.9666666666666667

Confusion Matrix: 
 [[11  0  0]
 [ 0 10  0]
 [ 0  1  8]]
