In [2]:

#20K-1682

from IPython.display import clear_output
import numpy as np
import random
import time
import gym

In [4]:
env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [5]:

action_size = env.action_space.n  # 6 = 0,1,2,3,4,5 as given in question
print("Action size ", action_size) 

state_size = env.observation_space.n  # 500 size as given in question
print("State size ", state_size)

Action size  6
State size  500


In [6]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:

#searched for these values
episodes = 30000            
max_steps = 1000            
lr = 0.3                    
decay_fac = 0.00001         
gamma = 0.90                

In [10]:
for episode in [30000]:
    
    state = env.reset() 
    done = False        
    lr -= decay_fac     
    step = 0
    
    if lr <= 0:
        break
        
    for step in range(max_steps):
        action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        if done == True:
            qtable[state, action] = qtable[state, action]+lr*(reward+gamma*0-qtable[state,action])
            break
        else:
            qtable[state, action] = qtable[state,action]+lr*(reward+gamma*np.max(qtable[new_state,:])-qtable[state,action])
        state = new_state
        
    episode += 1


In [11]:

state = env.reset()
env.render()
done = False
total_reward = 0

while(done == False):
    action = np.argmax(qtable[state,:])
    state, reward, done, info = env.step(action) 
    total_reward += reward 
    time.sleep(0.5)
    clear_output(wait=True)
    env.render()
    print('Reward = ', total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Reward =  10
